---
output:
  pdf_document:
    toc: yes
    toc_depth: '6'
params:
  gene: NA
editor_options: 
  chunk_output_type: console
---
```{r, echo=F, message=F, warning=F}

```

## Gene centric plot
```{r, echo=F, message=F, warning=F}
library(dplyr)
library(tidyverse)
library(data.table)
library(ggpubr)

vstlimma2 <- vstlimma %>%
  dplyr::mutate(ext_gene_ensembl = case_when(ext_gene == "" ~ ensembl_gene_id, 
                                      TRUE ~ ext_gene)) %>%
  #dplyr::select(ext_gene_ensembl, contains("SRR"))
  dplyr::select(-c(ensembl_gene_id, ext_gene)) %>% 
  dplyr::select(ext_gene_ensembl, everything()) # might be cleaner with relocate

res <- (samples) %>%
  mutate(., class = ifelse(condition == "mono", 'resistant', 'sensitive')) %>%
  dplyr::select(., SRR, class) %>%
  filter(., class == "resistant")


vst.goi <- as_tibble(vstlimma) %>%
  melt(.) %>%
  mutate(., class = ifelse(variable %in% res$SRR, 'resistant', 'sensitive'))
vst.goi <- readRDS("/Users/stephanie/Documents/GitHub/CancerDiscovery-Bulk/vst.goi.rds")
vst.goi$class <-
  factor(vst.goi$class, levels = c('sensitive', 'resistant'))

vst.goi$variable <- factor(vst.goi$variable)

#str(vst.goi)
#saveRDS(vst.goi, file = ("/Users/stephanie/Documents/GitHub/CancerDiscovery-Bulk/vst.goi.rds"))
colors <- c("#008080", "#DB4331")
datavst <-
  vst.goi[vst.goi$ext_gene == ("LSM14B") |
            vst.goi$ext_gene == ("KLF6") | vst.goi$ext_gene == ("BCL2"), ]

ggplot(datavst, aes(x = ext_gene, y = value, fill = class)) +
  geom_boxplot(outlier.shape = NA) +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  geom_point(alpha = 0.5, position = position_jitterdodge(jitter.width = 0.2), aes(color = class)) +
  theme_light() +
  ylab("Batch Corrected Variance Stabilized Data") +
  xlab("Gene") +
  ggtitle("Gene Expression:Sensitive vs Resistant")

```

## PCA plots
```{r, echo=F, message=F, warning=F}
##PCA Plot
#generate counts PCA data frame
samples <-
  data.frame(
    SRR = metadata$SRR,
    batch = metadata$batch,
    condition = metadata$sample_type,
    sample_name = metadata$DESeq_Sample_Name
  )

samples <- 
  samples[order(samples$SRR), ]

txi <-
  tximport(
    salm_dirs,
    type = 'salmon',
    tx2gene = tx2gene,
    ignoreTxVersion = TRUE
  )

ddsTxi <-
  DESeqDataSetFromTximport(txi, colData = samples, design = ~ batch + condition)


nonvsd.pca <-
  data.frame(prcomp(t(assay(ddsTxi)))$x) %>%
  as_tibble(rownames = "SRR") %>%
  left_join(., as_tibble(colData(ddsTxi))) %>% 
  dplyr::select(SRR, batch, condition, sample_name, everything())

saveRDS(nonvsd.pca, file = "/Users/stephanie/Documents/GitHub/CancerDiscovery-Bulk/nonvsd.pca.rds")
#stats
exp.pca.summary <- summary(nonvsd.pca)$importance
pc1var = round(exp.pca.summary[3,1] * 100, 1)
pc2var = round(exp.pca.summary[3,2] * 100 - pc1var, 1)
```


```{r, Counts PCA, echo= FALSE, fig.width=6, fig.height=4.5 }}
#generate counts PCA graph
colors <-
  c(viridis(15)[6], cividis(15)[9])
ggplot(nonvsd.pca, aes(x = PC1, y = PC2, fill = batch, shape = condition)) + 
  geom_point(size = 5) + 
  scale_shape_manual(values = c(21, 24), name = '') +
  scale_fill_manual(values = colors ) + 
  theme_classic(16) + xlab(paste('PC1')) + 
  ylab(paste('PC2')) +
  ggtitle("Non VSD") +
  guides(fill=guide_legend(override.aes = list(color=colors))) +
  geom_text_repel(aes(label=sample_name),hjust=0, vjust=0)

```

```{r, echo=F, message=F, warning=F}
# generate VST PCA
vsd <- vst(ddsTxi, blind = F)
vsd.pca <-
  data.frame(prcomp(t(assay(vsd)))$x) %>%
  as_tibble(rownames = "SRR") %>%
  left_join(., as_tibble(colData(vsd))) %>% 
  dplyr::select(SRR, batch, condition, sample_name, everything())

# stats
#exp.pca.summary <- summary(vsd.pca)$importance
#pc1var = round(exp.pca.summary[3,1] * 100, 1)
#pc2var = round(exp.pca.summary[3,2] * 100 - pc1var, 1)
```


```{r, VST PCA, echo=FALSE, fig.width=6, fig.height=4.5}
DESeq_Sample_Name<- metadata$DESeq_Sample_Name
sample_type<- metadata$sample_type
colors <- c(viridis(15)[6], cividis(15)[9])
ggplot(vsd.pca, aes(x = PC1, y = PC2, fill = sample_type, shape = condition)) + 
  geom_point(size = 5) + 
  scale_shape_manual(values = c(21, 24), name = '') +
  scale_fill_manual(values = colors ) + 
  theme_classic(16) + xlab(paste('PC1')) + 
  ylab(paste('PC2')) +
  ggtitle("Non VSD") +
  guides(fill=guide_legend(override.aes = list(color=colors))) +
  geom_text_repel(aes(label=DESeq_Sample_Name),hjust=0, vjust=0)

```

```{r, echo=F, message=F, warning=F}
#VST + batch corrected PCA
assay(vsd) <-
  limma::removeBatchEffect(assay(vsd),
                           batch = samples$batch,
                           design = model.matrix( ~ condition, data = samples))
# save the batch corrected vst data
vstlimmaPCA <-
  data.frame(assay(vsd)) %>%
  rownames_to_column(., var = "ensembl_gene_id") %>%
  left_join(unique(dplyr::select(t2g_hs, c(
    ensembl_gene_id, ext_gene
  ))), ., by = 'ensembl_gene_id') %>% na.omit(.)
#batch corrected bsd.pca data table
bcvsd.pca <-
  data.frame(prcomp(t(assay(vsd)))$x) %>%
  as_tibble(rownames = "SRR") %>%
  left_join(., as_tibble(colData(vsd))) %>% 
  dplyr::select(SRR, batch, condition, sample_name, everything())

```

```{r, Batch Corrected VST PCA, echo=F, fig.width=6, fig.height=4.5}
colors <- c(viridis(15)[6], cividis(15)[9])
ggplot(bcvsd.pca, aes(x = PC1, y = PC2, fill = batch, shape = condition)) + 
  geom_point(size = 5) + 
  scale_shape_manual(values = c(21, 24), name = '') +
  scale_fill_manual(values = colors ) + 
  theme_classic(16) + xlab(paste('PC1')) + 
  ylab(paste('PC2')) +
  ggtitle("Limma:VSD") +
  guides(fill=guide_legend(override.aes = list(color=colors))) +
  geom_text_repel(aes(label=sample_name),hjust=0, vjust=0)

```
## DE tables
```{r, include=F, message=F}
ddsTxi.filt <- ddsTxi[rowMins(counts(ddsTxi)) > 5,]
dds <- DESeq(ddsTxi.filt)
# add in gene names
dds.res <- data.frame(results(dds)) %>%
  rownames_to_column(., var = 'ensembl_gene_id') %>%
  dplyr::select(., ensembl_gene_id, baseMean, log2FoldChange, padj) %>%
  left_join(unique(dplyr::select(t2g_hs, c(
    ensembl_gene_id, ext_gene
  ))), ., by = 'ensembl_gene_id') %>%
  dplyr::rename(., Gene = ext_gene) %>%
  mutate(., DiffExp = ifelse(
    padj < 0.05 & log2FoldChange >= 0.5,
    'up',
    ifelse(padj < 0.05 &
             log2FoldChange <= -0.5, 'down', 'no')
  )) %>%
  na.omit(.)
#how many DEGs?
sum(dds.res$DiffExp == "yes")
sum(dds.res$DiffExp == "no")
sig.up <-
  dds.res[dds.res$DiffExp == 'yes' & dds.res$log2FoldChange > 1, ]
sig.down <-
  dds.res[dds.res$DiffExp == 'yes' & dds.res$log2FoldChange < 1, ]

# Table
dds.res %>%
  dplyr::filter(DiffExp %in% c("up", "down")) %>%
  dplyr::select(-baseMean,-DiffExp) %>%
  arrange(padj) %>%
  DT::datatable() %>% 
saveRDS(dds.res, file = "/Users/stephanie/Documents/GitHub/CancerDiscovery-Bulk/DEtable.rds")

#make the table interactive on shiny
#choose a gene or group of genes
# or filter out non significant gene padj <= 0.05, choose your threshold 
```
##DE Plot
```{r}
# Volcano
# pick from table what to show on plot
colors <-
  c(magma(15)[9], "grey", viridis(15)[10]) #use color palette for shiny
ggplot(data = dds.res, aes(
  x = log2FoldChange,
  y = -log10(padj),
  col = DiffExp
)) +
  geom_point() +
  theme_light() +
  scale_colour_manual(values = colors) +
  geom_text_repel(
    max.overlaps = 15,
    aes(label = ifelse(
      padj < 5e-20 &
        abs(log2FoldChange) >= 0.5,
      as.character(Gene), ""
    )),
    hjust = 0,
    vjust = 0
  ) +
  coord_cartesian(xlim = c(-10, 7))

```